function rectangle=rhull2rectangle(rhull);
% Timothee Cour, 12-Jun-2008 16:47:55 -- DO NOT DISTRIBUTE

rectangle=[...
    rhull(1),rhull(3);...
    rhull(2),rhull(3);...
    rhull(2),rhull(4);...
    rhull(1),rhull(4);];

%TODO:1 more line ?
